### ISSUE TITLE
devkit CSI sensor support?

### ISSUE THREAD

**Issue by AndreV84** [NVIDIA-AI-IOT/isaac_ros_apriltag#6]
is there a patch so it will use devkit CSI sensor instead of usb camera?

**Comment by hemalshahNV** [comment]
You should be able to replace the camera node with any equivalent image producer you want unless I misunderstood.

**Comment by AndreV84** [comment]
yes, there should be a file somewhere to adjust the gst pipeline to match nvargus

**Comment by hemalshahNV** [comment]
Closing as resolved.
